---
title: "eds-212-day-2"
author: "Jake Eisaguirre"
date: "8/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)

```

###A Find derivitive and slope
```{r}

A <- expression(x ^ 3)

D(expr = A, name = 'x' )

x <- 3

eval(expr = A)

```

###B Find derivitive and slope
```{r}

B <- expression (2 * ((3 * a + 2) ^ 4) - 5) 

D(expr = B, name = 'a')

a <- 1.2

eval(expr = B)

```

###C Find derivitive and slope
```{r}
C <- expression ((-4 * t) / (t ^ 2 + 1) ^ 3)

D(expr = C, name= 't')

t <- 0

eval(expr = C)


```

### Univariate derivitives 
```{r}
D <- expression(4.6 - (1.9 * z ^ 3))

D1 <- D(expr = D, name = 'z')

D1

D2 <- D(expr = D1, name = 'z')

D2


```
### Partial derivitives
```{r}
f_xyz <- expression((2 * (x ^ 2) * y) - (3 * x) + 1 + (4 * (z ^ 4) * x))

Dx <- D(expr = f_xyz, name = 'x')

Dx

Dy <- D(expr = f_xyz, name = 'y')

Dy

Dz <- D(expr = f_xyz, name = 'z')

Dz

```

### Make some plots

```{r}
fx <- function(x) {
  2.4 * exp(-0.05 * x) * sin(x)
}

ggplot(data = data.frame(x = c(-0.5, 0.5)), aes(x=x)) + stat_function(fun = fx)
```

### Penguin bill length vs bill depth
```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(aes(color = species)) + labs(x='bill length (mm)', y='bill depth (mm)', title = 'Palmer Penguins')


```
### Jitter Plot
```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_jitter(aes(color = species), width=0.1) + labs(x='Species', y='flipper length (mm)', title = 'Palmer Penguins')

```

